"""New Migration

Revision ID: d4a07749aa7c
Revises: aee24b2db1c8
Create Date: 2026-01-25 17:30:49.087737

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd4a07749aa7c'
down_revision = 'aee24b2db1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
